[package]
name = "chip-8"
version = "0.1.0"
authors = ["Vahan Boghossian"]
edition = "2018"

[dependencies]
minifb = "0.19"
rand = "0.8"

[features]
default = ["quirky_shift", "quirky_restore"]
quirky_shift = []
quirky_restore = []
